<?php
require_once __DIR__.'/app/classes/BaseDeDonnees.php'; require_once __DIR__.'/app/classes/Session.php'; require_once __DIR__.'/app/helpers.php';
$u=current_user(); $db=db(); $type=$_GET['type'] ?? 'public'; $coursId=(int)($_GET['cours_id'] ?? 1); $otherId=(int)($_GET['user_id'] ?? 0); $title='Conversation'; $messages=[];
if($type==='prive' && $otherId){ $other=$db->prepare('SELECT * FROM users WHERE id=?'); $other->execute([$otherId]); $other=$other->fetch(); if(!$other){die('Contact introuvable');} $title='Privé avec '.$other['nom']; $st=$db->prepare('SELECT m.*, u.nom auteur, f.url,f.nom_original,f.type ftype,f.taille FROM messages m JOIN users u ON u.id=m.expediteur_id LEFT JOIN fichiers f ON f.message_id=m.id WHERE m.type="prive" AND ((m.expediteur_id=? AND m.destinataire_id=?) OR (m.expediteur_id=? AND m.destinataire_id=?)) ORDER BY m.created_at'); $st->execute([$u['id'],$otherId,$otherId,$u['id']]); $messages=$st->fetchAll(); }
else { $cours=$db->prepare('SELECT * FROM cours WHERE id=?'); $cours->execute([$coursId]); $cours=$cours->fetch(); $title=$cours ? $cours['nom'].' — mur public' : 'Mur public'; $st=$db->prepare('SELECT m.*, u.nom auteur, f.url,f.nom_original,f.type ftype,f.taille FROM messages m JOIN users u ON u.id=m.expediteur_id LEFT JOIN fichiers f ON f.message_id=m.id WHERE m.cours_id=? AND m.type IN ("public","mur_pedagogique") ORDER BY m.created_at'); $st->execute([$coursId]); $messages=$st->fetchAll(); }
?>
<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($title)?></title><link rel="stylesheet" href="assets/css/style.css"></head><body><aside class="sidebar"><div class="brand small"><div class="logo">💬</div><div><h2>FasiChat</h2><p><?=h(role_label($u['role']))?></p></div></div><nav><a href="dashboard.php">⬅ Retour</a><a href="valve.php">📣 Valve</a><a href="logout.php">🚪 Déconnexion</a></nav></aside>
<main class="chat"><header class="chat-head"><h1><?=h($title)?></h1><span class="pill"><?= $type==='prive'?'Message privé':'Message public' ?></span></header><section id="messages" class="messages">
<?php foreach($messages as $m): $mine=$m['expediteur_id']==$u['id']; ?><div class="msg <?=$mine?'mine':''?>"><div class="avatar"><?=h(mb_substr($m['auteur'],0,2))?></div><div class="bubble"><b><?=h($m['auteur'])?></b><?php if($m['contenu']): ?><p><?=nl2br(h($m['contenu']))?></p><?php endif; ?><?php if($m['url']): ?><a class="file" target="_blank" href="<?=h($m['url'])?>">📎 <?=h($m['nom_original'])?> <small><?=round($m['taille']/1024/1024,1)?> Mo</small></a><?php endif; ?><time><?=h($m['created_at'])?></time></div></div><?php endforeach; ?></section>
<form class="composer" id="msgForm" enctype="multipart/form-data"><input type="hidden" name="type" value="<?=h($type)?>"><input type="hidden" name="cours_id" value="<?=$coursId?>"><input type="hidden" name="receiver_id" value="<?=$otherId?>"><textarea name="contenu" placeholder="Écrire un message..."></textarea><div class="tools"><label>📎 Fichier<input type="file" name="fichier" hidden></label><button type="button" id="audioBtn">🎤 Audio</button><button>Envoyer ➜</button></div></form></main><script src="assets/js/chat.js"></script></body></html>
