CREATE DATABASE IF NOT EXISTS fasichat_classroom CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fasichat_classroom;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS fichiers, messages, convocation_destinataires, convocations, annonces_valve, enseignement, inscriptions, cours, promotions, users;
SET FOREIGN_KEY_CHECKS=1;
CREATE TABLE promotions(id INT AUTO_INCREMENT PRIMARY KEY, nom VARCHAR(100) NOT NULL, annee VARCHAR(20));
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY, nom VARCHAR(120) NOT NULL, identifiant VARCHAR(120) UNIQUE NOT NULL, password_hash VARCHAR(255) NOT NULL, role ENUM('etudiant','enseignant','assistant','doyen','vice_doyen','apparitaire') NOT NULL, promotion_id INT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(promotion_id) REFERENCES promotions(id));
CREATE TABLE cours(id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50), nom VARCHAR(150) NOT NULL, description TEXT, promotion_id INT, FOREIGN KEY(promotion_id) REFERENCES promotions(id));
CREATE TABLE inscriptions(user_id INT, cours_id INT, PRIMARY KEY(user_id,cours_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(cours_id) REFERENCES cours(id) ON DELETE CASCADE);
CREATE TABLE enseignement(user_id INT, cours_id INT, PRIMARY KEY(user_id,cours_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(cours_id) REFERENCES cours(id) ON DELETE CASCADE);
CREATE TABLE messages(id INT AUTO_INCREMENT PRIMARY KEY, expediteur_id INT NOT NULL, destinataire_id INT NULL, cours_id INT NULL, type ENUM('prive','public','mur_pedagogique') NOT NULL, contenu TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(expediteur_id) REFERENCES users(id), FOREIGN KEY(destinataire_id) REFERENCES users(id), FOREIGN KEY(cours_id) REFERENCES cours(id));
CREATE TABLE fichiers(id INT AUTO_INCREMENT PRIMARY KEY, message_id INT NOT NULL, nom_original VARCHAR(255), nom_stocke VARCHAR(255), url VARCHAR(255), mime VARCHAR(120), type VARCHAR(40), taille INT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE);
CREATE TABLE convocations(id INT AUTO_INCREMENT PRIMARY KEY, auteur_id INT NOT NULL, objet VARCHAR(180), date_heure DATETIME, lieu VARCHAR(255), message TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(auteur_id) REFERENCES users(id));
CREATE TABLE convocation_destinataires(convocation_id INT, user_id INT, lu TINYINT DEFAULT 0, PRIMARY KEY(convocation_id,user_id), FOREIGN KEY(convocation_id) REFERENCES convocations(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE annonces_valve(id INT AUTO_INCREMENT PRIMARY KEY, auteur_id INT NOT NULL, titre VARCHAR(180), contenu TEXT, categorie ENUM('urgence','convocation','info','academique') DEFAULT 'info', date_publication DATETIME DEFAULT CURRENT_TIMESTAMP, date_expiration DATE NULL, FOREIGN KEY(auteur_id) REFERENCES users(id));
INSERT INTO promotions(nom,annee) VALUES('L2 Sciences Informatiques','2025-2026');
INSERT INTO users(nom,identifiant,password_hash,role,promotion_id) VALUES
('Samuel Banzolele','SI2024001','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','etudiant',1),('Ezechiel Itewe','SI2024002','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','etudiant',1),('Beloved Mazua','SI2024003','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','etudiant',1),('Dan Bakenda','SI2024004','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','etudiant',1),('Audrey Musengi','SI2024005','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','etudiant',1),('Bellvie Ipuna','SI2024006','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','etudiant',1),
('Prof. Mampuya','enseignant@faculte.edu','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','enseignant',NULL),('Ass. Bahati','assistant@faculte.edu','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','assistant',NULL),('Pr. Kutangila','doyen@faculte.edu','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','doyen',NULL),('Pr. Manpuya','vdoyen@faculte.edu','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','vice_doyen',NULL),('DJ. Rolly','apparitaire@faculte.edu','$2y$12$00sD0SzSa/lwmJgJl/o/GO62ZUIRGoRgyW2q483/A18NDtjPylfVy','apparitaire',NULL);
INSERT INTO cours(code,nom,description,promotion_id) VALUES('PHP-POO','PHP POO — Promo L2','Programmation Web en PHP orienté objet, classes, héritage, PDO et sécurité.',1),('SYS-EMB','Système embarqué','Introduction aux systèmes embarqués.',1),('MERISE','Base de données et Merise','Modélisation et conception de base de données.',1);
INSERT INTO inscriptions(user_id,cours_id) SELECT u.id,c.id FROM users u JOIN cours c WHERE u.role='etudiant';
INSERT INTO enseignement(user_id,cours_id) VALUES(7,1),(8,1),(8,2);
INSERT INTO messages(expediteur_id,cours_id,type,contenu,created_at) VALUES(7,1,'mur_pedagogique','Bonjour à tous ! Rappel : les projets FasiChat sont à rendre avant vendredi. Respectez les principes de la POO.','2026-06-10 08:45:00'),(2,1,'public','Merci Professeur, est-ce que le rapport est obligatoire ou optionnel ?','2026-06-10 09:10:00'),(7,1,'public','La conception est obligatoire et compte pour 6 points sur 20.','2026-06-10 09:15:00');
INSERT INTO messages(expediteur_id,destinataire_id,type,contenu,created_at) VALUES(2,1,'prive','Salut Samuel, tu as déjà avancé sur la partie fichiers ?',NOW()),(1,3,'prive','On se voit demain pour tester le projet.',NOW());
INSERT INTO annonces_valve(auteur_id,titre,contenu,categorie) VALUES(11,'Modification du calendrier des examens','Le calendrier des examens de rattrapage a été modifié. Consultez régulièrement la Valve.','urgence'),(11,'Dépôt des projets PHP','Les projets PHP POO doivent être déposés sur GitHub avec le fichier SQL.','academique'),(11,'Réunion pédagogique','Une réunion pédagogique est prévue avec les enseignants et assistants.','convocation');
INSERT INTO convocations(auteur_id,objet,date_heure,lieu,message) VALUES(9,'Réunion du conseil pédagogique','2026-06-24 10:00:00','Salle du conseil','Préparation de la session et suivi des projets.');
INSERT INTO convocation_destinataires(convocation_id,user_id) VALUES(1,7),(1,8);
